/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {type: "doc", id: "intro"},
    {type: "doc", id: "tutorial-basics/cara-buat-akun"},
    {
      type: "category",
      label: "Campaign / Broadcast",
      items: [
        {
          type: "doc",
          id: "tutorial-basics/cara-membuat-campaign-whatsapp",
          label: "Cara membuat campaign / broadcast di WhatsApp",
        },
        {
          type: "doc",
          id: "tutorial-basics/cara-broadcast-whatsapp-business",
          label: "Cara membuat campaign / broadcast di whatsapp business",
        },
      ],
    },
    {type: "doc", id: "tutorial-basics/integrasi-google-forms-whatsapp"},
    { type: "autogenerated", dirName: "tutorial-extras" },
  ],
  openApiSidebar: [
    {
      type: "category",
      label: "API Reference",
      link: {
        type: "generated-index",
        title: "Chatbotnesia API",
        description:
          "This is a sample server Chatbotnesia server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/category/chatbotnesia-api"
      },
      items: require("./docs/chatbotnesia/sidebar.js")
    }
  ]
};

export default sidebars;